### ISSUE TITLE
practica lógica proposicional y tablas de verdad

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-saul-lopez-bautista#1]
[PRACTICA LOGICA PROPOSICIONAL Y TABLAS DE VERDAD.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-saul-lopez-bautista/files/7458331/PRACTICA.LOGICA.PROPOSICIONAL.Y.TABLAS.DE.VERDAD.pdf)

**Comment by 7177981** [comment]
[PRACTICA LOGICA PROPOSICIONAL Y TABLAS DE VERDAD.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-saul-lopez-bautista/files/7472047/PRACTICA.LOGICA.PROPOSICIONAL.Y.TABLAS.DE.VERDAD.pdf)

**Comment by 71santiago7** [comment]
excelente trabajo contiene todo lo que pide la rubrica esta practica equivale
20%

**Comment by 71santiago7** [comment]
excelente trabajo contiene todo lo que pide la rubrica esta practica equivale
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
