### ISSUE TITLE
PRACTICA LOGICA PROPOSICIONAL Y TABLAS DE VERDAD

### ISSUE THREAD

**Issue by 7177981** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-saul-lopez-bautista#2]
[Uploading PRACTICA LOGICA PROPOSICIONAL Y TABLAS DE VERDAD.pdf…]()

**Comment by 71santiago7** [comment]
excelente   trabajo   contiene  todo  lo que  pide  la rubrica esta  practica equivale 
 20%

**Comment by 71santiago7** [comment]
excelente trabajo contiene todo lo que pide la rubrica esta practica equivale
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
