### ISSUE TITLE
Practica logica proposicional y tablas de verdad

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-saul-lopez-bautista#3]
[Uploading Practica logica proposicional y tablas de verdad.pdf…]()

**Comment by yanet02** [comment]
Portada (25%)
Procedimiento(22%) faltó la descripción y resultados.
Figuras, ilustraciónes y fotografías(25%) 
Resultados y conclusiónes(22%)  faltó resultados.
Total = 94%
Calificación=28.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
